/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'submitted' : IDL.Null,
  'answered' : IDL.Null,
  'prayedFor' : IDL.Null,
});
export const Email = IDL.Text;
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'joy' : IDL.Null,
  'perseverance' : IDL.Null,
  'deliverance' : IDL.Null,
  'thanksgiving' : IDL.Null,
  'other' : IDL.Text,
  'hope' : IDL.Null,
  'love' : IDL.Null,
  'education' : IDL.Null,
  'salvation' : IDL.Null,
  'wisdom' : IDL.Null,
  'forgiveness' : IDL.Null,
  'healing' : IDL.Null,
  'marriage' : IDL.Null,
  'career' : IDL.Null,
  'peace' : IDL.Null,
  'guidance' : IDL.Null,
  'patience' : IDL.Null,
  'family' : IDL.Null,
  'testimony' : IDL.Null,
  'finances' : IDL.Null,
  'faith' : IDL.Null,
});
export const PhoneNumber = IDL.Nat;
export const PrayerRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'name' : IDL.Text,
  'email' : IDL.Opt(Email),
  'message' : IDL.Text,
  'timestamp' : Time,
  'category' : Category,
  'phone' : IDL.Opt(PhoneNumber),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPrayerRequestsByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(PrayerRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPrayerRequest' : IDL.Func(
      [IDL.Text, IDL.Opt(PhoneNumber), IDL.Opt(Email), Category, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updatePrayerRequestStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'submitted' : IDL.Null,
    'answered' : IDL.Null,
    'prayedFor' : IDL.Null,
  });
  const Email = IDL.Text;
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'joy' : IDL.Null,
    'perseverance' : IDL.Null,
    'deliverance' : IDL.Null,
    'thanksgiving' : IDL.Null,
    'other' : IDL.Text,
    'hope' : IDL.Null,
    'love' : IDL.Null,
    'education' : IDL.Null,
    'salvation' : IDL.Null,
    'wisdom' : IDL.Null,
    'forgiveness' : IDL.Null,
    'healing' : IDL.Null,
    'marriage' : IDL.Null,
    'career' : IDL.Null,
    'peace' : IDL.Null,
    'guidance' : IDL.Null,
    'patience' : IDL.Null,
    'family' : IDL.Null,
    'testimony' : IDL.Null,
    'finances' : IDL.Null,
    'faith' : IDL.Null,
  });
  const PhoneNumber = IDL.Nat;
  const PrayerRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'name' : IDL.Text,
    'email' : IDL.Opt(Email),
    'message' : IDL.Text,
    'timestamp' : Time,
    'category' : Category,
    'phone' : IDL.Opt(PhoneNumber),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPrayerRequests' : IDL.Func([], [IDL.Vec(PrayerRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPrayerRequestsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(PrayerRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPrayerRequest' : IDL.Func(
        [IDL.Text, IDL.Opt(PhoneNumber), IDL.Opt(Email), Category, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updatePrayerRequestStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };