/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'joy' : null } |
  { 'perseverance' : null } |
  { 'deliverance' : null } |
  { 'thanksgiving' : null } |
  { 'other' : string } |
  { 'hope' : null } |
  { 'love' : null } |
  { 'education' : null } |
  { 'salvation' : null } |
  { 'wisdom' : null } |
  { 'forgiveness' : null } |
  { 'healing' : null } |
  { 'marriage' : null } |
  { 'career' : null } |
  { 'peace' : null } |
  { 'guidance' : null } |
  { 'patience' : null } |
  { 'family' : null } |
  { 'testimony' : null } |
  { 'finances' : null } |
  { 'faith' : null };
export type Email = string;
export type PhoneNumber = bigint;
export interface PrayerRequest {
  'id' : bigint,
  'status' : Status,
  'name' : string,
  'email' : [] | [Email],
  'message' : string,
  'timestamp' : Time,
  'category' : Category,
  'phone' : [] | [PhoneNumber],
}
export type Status = { 'submitted' : null } |
  { 'answered' : null } |
  { 'prayedFor' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPrayerRequests' : ActorMethod<[], Array<PrayerRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPrayerRequestsByCategory' : ActorMethod<[Category], Array<PrayerRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPrayerRequest' : ActorMethod<
    [string, [] | [PhoneNumber], [] | [Email], Category, string],
    bigint
  >,
  'updatePrayerRequestStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];