/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PhoneNumber = bigint;
export type Category = {
    __kind__: "joy";
    joy: null;
} | {
    __kind__: "perseverance";
    perseverance: null;
} | {
    __kind__: "deliverance";
    deliverance: null;
} | {
    __kind__: "thanksgiving";
    thanksgiving: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "hope";
    hope: null;
} | {
    __kind__: "love";
    love: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "salvation";
    salvation: null;
} | {
    __kind__: "wisdom";
    wisdom: null;
} | {
    __kind__: "forgiveness";
    forgiveness: null;
} | {
    __kind__: "healing";
    healing: null;
} | {
    __kind__: "marriage";
    marriage: null;
} | {
    __kind__: "career";
    career: null;
} | {
    __kind__: "peace";
    peace: null;
} | {
    __kind__: "guidance";
    guidance: null;
} | {
    __kind__: "patience";
    patience: null;
} | {
    __kind__: "family";
    family: null;
} | {
    __kind__: "testimony";
    testimony: null;
} | {
    __kind__: "finances";
    finances: null;
} | {
    __kind__: "faith";
    faith: null;
};
export type Time = bigint;
export interface PrayerRequest {
    id: bigint;
    status: Status;
    name: string;
    email?: Email;
    message: string;
    timestamp: Time;
    category: Category;
    phone?: PhoneNumber;
}
export interface UserProfile {
    name: string;
    email: string;
}
export type Email = string;
export enum Status {
    submitted = "submitted",
    answered = "answered",
    prayedFor = "prayedFor"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllPrayerRequests(): Promise<Array<PrayerRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPrayerRequestsByCategory(category: Category): Promise<Array<PrayerRequest>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPrayerRequest(name: string, phone: PhoneNumber | null, email: Email | null, category: Category, message: string): Promise<bigint>;
    updatePrayerRequestStatus(id: bigint, status: Status): Promise<void>;
}
import type { Category as _Category, Email as _Email, PhoneNumber as _PhoneNumber, PrayerRequest as _PrayerRequest, Status as _Status, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllPrayerRequests(): Promise<Array<PrayerRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrayerRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrayerRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrayerRequestsByCategory(arg0: Category): Promise<Array<PrayerRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrayerRequestsByCategory(to_candid_Category_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrayerRequestsByCategory(to_candid_Category_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPrayerRequest(arg0: string, arg1: PhoneNumber | null, arg2: Email | null, arg3: Category, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPrayerRequest(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n15(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPrayerRequest(arg0, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n18(this._uploadFile, this._downloadFile, arg2), to_candid_Category_n15(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updatePrayerRequestStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrayerRequestStatus(arg0, to_candid_Status_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrayerRequestStatus(arg0, to_candid_Status_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_PrayerRequest_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrayerRequest): PrayerRequest {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PhoneNumber]): PhoneNumber | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Email]): Email | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    name: string;
    email: [] | [_Email];
    message: string;
    timestamp: _Time;
    category: _Category;
    phone: [] | [_PhoneNumber];
}): {
    id: bigint;
    status: Status;
    name: string;
    email?: Email;
    message: string;
    timestamp: Time;
    category: Category;
    phone?: PhoneNumber;
} {
    return {
        id: value.id,
        status: from_candid_Status_n6(_uploadFile, _downloadFile, value.status),
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.email)),
        message: value.message,
        timestamp: value.timestamp,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        phone: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    joy: null;
} | {
    perseverance: null;
} | {
    deliverance: null;
} | {
    thanksgiving: null;
} | {
    other: string;
} | {
    hope: null;
} | {
    love: null;
} | {
    education: null;
} | {
    salvation: null;
} | {
    wisdom: null;
} | {
    forgiveness: null;
} | {
    healing: null;
} | {
    marriage: null;
} | {
    career: null;
} | {
    peace: null;
} | {
    guidance: null;
} | {
    patience: null;
} | {
    family: null;
} | {
    testimony: null;
} | {
    finances: null;
} | {
    faith: null;
}): {
    __kind__: "joy";
    joy: null;
} | {
    __kind__: "perseverance";
    perseverance: null;
} | {
    __kind__: "deliverance";
    deliverance: null;
} | {
    __kind__: "thanksgiving";
    thanksgiving: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "hope";
    hope: null;
} | {
    __kind__: "love";
    love: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "salvation";
    salvation: null;
} | {
    __kind__: "wisdom";
    wisdom: null;
} | {
    __kind__: "forgiveness";
    forgiveness: null;
} | {
    __kind__: "healing";
    healing: null;
} | {
    __kind__: "marriage";
    marriage: null;
} | {
    __kind__: "career";
    career: null;
} | {
    __kind__: "peace";
    peace: null;
} | {
    __kind__: "guidance";
    guidance: null;
} | {
    __kind__: "patience";
    patience: null;
} | {
    __kind__: "family";
    family: null;
} | {
    __kind__: "testimony";
    testimony: null;
} | {
    __kind__: "finances";
    finances: null;
} | {
    __kind__: "faith";
    faith: null;
} {
    return "joy" in value ? {
        __kind__: "joy",
        joy: value.joy
    } : "perseverance" in value ? {
        __kind__: "perseverance",
        perseverance: value.perseverance
    } : "deliverance" in value ? {
        __kind__: "deliverance",
        deliverance: value.deliverance
    } : "thanksgiving" in value ? {
        __kind__: "thanksgiving",
        thanksgiving: value.thanksgiving
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "hope" in value ? {
        __kind__: "hope",
        hope: value.hope
    } : "love" in value ? {
        __kind__: "love",
        love: value.love
    } : "education" in value ? {
        __kind__: "education",
        education: value.education
    } : "salvation" in value ? {
        __kind__: "salvation",
        salvation: value.salvation
    } : "wisdom" in value ? {
        __kind__: "wisdom",
        wisdom: value.wisdom
    } : "forgiveness" in value ? {
        __kind__: "forgiveness",
        forgiveness: value.forgiveness
    } : "healing" in value ? {
        __kind__: "healing",
        healing: value.healing
    } : "marriage" in value ? {
        __kind__: "marriage",
        marriage: value.marriage
    } : "career" in value ? {
        __kind__: "career",
        career: value.career
    } : "peace" in value ? {
        __kind__: "peace",
        peace: value.peace
    } : "guidance" in value ? {
        __kind__: "guidance",
        guidance: value.guidance
    } : "patience" in value ? {
        __kind__: "patience",
        patience: value.patience
    } : "family" in value ? {
        __kind__: "family",
        family: value.family
    } : "testimony" in value ? {
        __kind__: "testimony",
        testimony: value.testimony
    } : "finances" in value ? {
        __kind__: "finances",
        finances: value.finances
    } : "faith" in value ? {
        __kind__: "faith",
        faith: value.faith
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    answered: null;
} | {
    prayedFor: null;
}): Status {
    return "submitted" in value ? Status.submitted : "answered" in value ? Status.answered : "prayedFor" in value ? Status.prayedFor : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrayerRequest>): Array<PrayerRequest> {
    return value.map((x)=>from_candid_PrayerRequest_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PhoneNumber | null): [] | [_PhoneNumber] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Email | null): [] | [_Email] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "joy";
    joy: null;
} | {
    __kind__: "perseverance";
    perseverance: null;
} | {
    __kind__: "deliverance";
    deliverance: null;
} | {
    __kind__: "thanksgiving";
    thanksgiving: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "hope";
    hope: null;
} | {
    __kind__: "love";
    love: null;
} | {
    __kind__: "education";
    education: null;
} | {
    __kind__: "salvation";
    salvation: null;
} | {
    __kind__: "wisdom";
    wisdom: null;
} | {
    __kind__: "forgiveness";
    forgiveness: null;
} | {
    __kind__: "healing";
    healing: null;
} | {
    __kind__: "marriage";
    marriage: null;
} | {
    __kind__: "career";
    career: null;
} | {
    __kind__: "peace";
    peace: null;
} | {
    __kind__: "guidance";
    guidance: null;
} | {
    __kind__: "patience";
    patience: null;
} | {
    __kind__: "family";
    family: null;
} | {
    __kind__: "testimony";
    testimony: null;
} | {
    __kind__: "finances";
    finances: null;
} | {
    __kind__: "faith";
    faith: null;
}): {
    joy: null;
} | {
    perseverance: null;
} | {
    deliverance: null;
} | {
    thanksgiving: null;
} | {
    other: string;
} | {
    hope: null;
} | {
    love: null;
} | {
    education: null;
} | {
    salvation: null;
} | {
    wisdom: null;
} | {
    forgiveness: null;
} | {
    healing: null;
} | {
    marriage: null;
} | {
    career: null;
} | {
    peace: null;
} | {
    guidance: null;
} | {
    patience: null;
} | {
    family: null;
} | {
    testimony: null;
} | {
    finances: null;
} | {
    faith: null;
} {
    return value.__kind__ === "joy" ? {
        joy: value.joy
    } : value.__kind__ === "perseverance" ? {
        perseverance: value.perseverance
    } : value.__kind__ === "deliverance" ? {
        deliverance: value.deliverance
    } : value.__kind__ === "thanksgiving" ? {
        thanksgiving: value.thanksgiving
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "hope" ? {
        hope: value.hope
    } : value.__kind__ === "love" ? {
        love: value.love
    } : value.__kind__ === "education" ? {
        education: value.education
    } : value.__kind__ === "salvation" ? {
        salvation: value.salvation
    } : value.__kind__ === "wisdom" ? {
        wisdom: value.wisdom
    } : value.__kind__ === "forgiveness" ? {
        forgiveness: value.forgiveness
    } : value.__kind__ === "healing" ? {
        healing: value.healing
    } : value.__kind__ === "marriage" ? {
        marriage: value.marriage
    } : value.__kind__ === "career" ? {
        career: value.career
    } : value.__kind__ === "peace" ? {
        peace: value.peace
    } : value.__kind__ === "guidance" ? {
        guidance: value.guidance
    } : value.__kind__ === "patience" ? {
        patience: value.patience
    } : value.__kind__ === "family" ? {
        family: value.family
    } : value.__kind__ === "testimony" ? {
        testimony: value.testimony
    } : value.__kind__ === "finances" ? {
        finances: value.finances
    } : value.__kind__ === "faith" ? {
        faith: value.faith
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    submitted: null;
} | {
    answered: null;
} | {
    prayedFor: null;
} {
    return value == Status.submitted ? {
        submitted: null
    } : value == Status.answered ? {
        answered: null
    } : value == Status.prayedFor ? {
        prayedFor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
